stages:
    - verify
    - build
    - test

cache:
    untracked: true
    paths:
        - vendor

variables:
    TERM: xterm-256color
    GO_GETFLAGS:
    GO_BUILDFLAGS: -ldflags "-s -w"
    GOFMTFLAGS: -d

before_script:
    - apt-get update -qq -y
    - apt-get install -qq -y make git colordiff

image: golang:1.9

fmt:
    stage: verify
    script:
        - make $CI_JOB_NAME > diff
        - cat diff | colordiff
        - test $(cat diff | wc -l) -eq 0

vet:
    stage: verify
    script:
        - make $CI_JOB_NAME

build/alpine:
    image: golang:1.9-alpine
    stage: build
    before_script:
        - apk update -qq
        - apk add -qq make git
    script:
        - make $CI_JOB_NAME

build/darwin:
    stage: build
    script:
        - make $CI_JOB_NAME

build/linux:
    stage: build
    script:
        - make $CI_JOB_NAME

build/windows:
    stage: build
    script:
        - make $CI_JOB_NAME

linux:
    stage: test
    script:
        - bin/$CI_JOB_NAME/local-ci

alpine:
    image: golang:1.9-alpine
    stage: test
    before_script:
        - apk update
        - apk add make git
    script:
        - bin/$CI_JOB_NAME/local-ci
